### ISSUE TITLE
support for Apache logs

### ISSUE THREAD

**Issue by pdurbin** [CDLUC3/counter-processor#3]
Hi! I'm entering via https://github.com/CDLUC3/Make-Data-Count/issues/99 and I'm trying to get a sense of if it makes sense for Dataverse to use counter-processor.

The README says, "The software assumes you area already logging your COUNTER dataset investigations and requests to a log file using a format somewhat similar to extended log format. The COUNTER Code of Practice requires that descriptive metadata be submitted along with statistics--these items are included in logs to ease later processing."

Over at sample_logs/counter_2018-05-08.log I'm seeing the following example line:

`2018-05-08T00:00:40-07:00 128.195.188.234 - - - http://dash.lib.uci.edu/stash/dataset/doi:10.7280/D1H01B doi:10.7280/D1H01B - - uci-google-search-appliance (Enterprise; T4-CGX5LF9EL8JCP; eus@uci.edu,jkreuzig@uci.edu,mehrenbe@uci.edu) Mustard Removal Experiment at Bayview Slope UC Irvine grid.266093.8 Riley Pratt|Jessica Pratt|Jenny Talbot|Stephanie Kivlin|Margaret Royall-Reed|Steven D. Allison 2015-04-14T11:00:46Z 1 - https://dash.lib.uci.edu/stash/dataset/doi:10.7280/D1H01B 2015`

In order to make this line more readable, I'm converting it to YAML with https://github.com/brendano/tsvutils/blob/master/tsv2yaml

```
event_time: '2018-05-08T00:00:40-07:00'
client_ip: 128.195.188.234
session_cookie_id: '-'
user_cookie_id: '-'
user_id: '-'
request_url: http://dash.lib.uci.edu/stash/dataset/doi:10.7280/D1H01B
identifier: doi:10.7280/D1H01B
filename: '-'
size: '-'
user-agent: uci-google-search-appliance (Enterprise; T4-CGX5LF9EL8JCP; eus@uci.edu,jkreuzig@uci.edu,mehrenbe@uci.edu)
title: Mustard Removal Experiment at Bayview Slope
publisher: UC Irvine
publisher_id: grid.266093.8
authors: Riley Pratt|Jessica Pratt|Jenny Talbot|Stephanie Kivlin|Margaret Royall-Reed|Steven
  D. Allison
publication_date: '2015-04-14T11:00:46Z'
version: '1'
other_id: '-'
target_url: https://dash.lib.uci.edu/stash/dataset/doi:10.7280/D1H01B
publication_year: '2015'
```

Above I can see all the descriptive metadata mentioned in the README such as title, publisher, authors, etc.

In contrast, the logs I have are just standard Apache logs. If enabled, Glassfish access logs are also available to Dataverse installations. They look like this:

## Apache

`65.112.10.92 - - [26/Nov/2018:14:27:37 -0500] "GET /dataset.xhtml?persistentId=doi:10.5072/FK2/FS7M3O HTTP/1.1" 200 147348`

Example Apache log location: /var/log/httpd/ssl_access_log

## Glassfish

`"65.112.10.92" "NULL-AUTH-USER" "26/Nov/2018:14:27:40 -0500" "GET /dataset.xhtml?persistentId=doi:10.5072/FK2/FS7M3O HTTP/1.1" 200 147342`

Example Glassfish log location: /usr/local/glassfish4/glassfish/domains/domain1/logs/access/server_access_log.2018-11-26.txt

Obviously, standard Apache logs don't have descriptive metadata such as title, publisher, author in them. I'm basically answering my own question at this point. Basically, I came to the README wondering if my existing Apache logs could be parsed to create the reports we need to send to the DataCite hub but the answer is no. The data repository software (Dataverse, in this case) needs to emit logs in a specific format, as described in the README, before "counter-processor" can be used on it. Now that I have a better understanding of the tool, I'll update my to do list at https://github.com/IQSS/dataverse/issues/4821#issuecomment-440327789 and explain to people on the Dataverse team the situation. Thanks for listening. I'm happy to discuss all this. Or I'm happy to close this issue sooner rather than later if it's just noise. I thought the new user experience might be valuable to you. 😄

**Comment by sfisher** [comment]
This tool really doesn't work for anything but specific-format logging right now.  It could be modified to do metadata lookups during processing or report export rather than logging it, but of course, that increases the amount of code and adds some complexity.

It is really designed for our own use case and all the metadata was available to us at log time so it was the most direct path forward for us to simply log it.  While the metadata increases the log sizes, storage is cheap and the logs also compress well.  I understand that it would be useful to be a much more flexible tool and it seems to me that some people who don't understand much about this tool have oversold it for more than it really is at the moment.  Right now it would require other log formats to massage their data into this specific format to work (and I know it's probably not-at-all ideal for everyone to do that).

The code could use much more work and certainly adding additional features would also be nice.  I'd also like to clean up some parts of the code that are a bit problematic (since COUNTER report requirements were continually changing while I was writing this and I had very limited time to deal with changes or refactor code). I don't see much work with revisions coming from me anytime in the next several months because I have a very long list of other work priorities scheduled.

Sorry it was a bit disappointing for your use case.  When I'm less resource starved, I may be able to get back to this.

**Comment by pdurbin** [comment]
@sfisher hi! When I opened this issue I was still grappling with what Make Data Count is and the role of Counter Processor. I understand well now that a specialized log format is required so I'll close this issue. I did want to let you know that over in Dataverse land our working plan is to at least start by using Counter Processor so thanks for making this open source! I'll include below our latest architecture diagram, which is subject to change, since it's still early days for us.

![50841935-c02dd600-1333-11e9-87ed-2ecbe742b6e6](https://user-images.githubusercontent.com/21006/50865780-26871880-1375-11e9-9b58-33a53c8931da.png)

Thanks again!
